### PR TITLE
Homepage redesign

### PR DESCRIPTION
**Pull request by AKSHATH99**
Redesigned call to action section of recipe submission and explore section in home page . 

Issue #15

### CODE REVIEW

**Comment by rudalkunwar** [comment]
can you make it mobile responsive too

**Comment by AKSHATH99** [comment]
Yeah .

**Comment by rudalkunwar** [comment]
thanks for the contribution

**Comment by AKSHATH99** [comment]
Yeah . Can i work on designing a form page for submitting recipe ?

**Pull request merged**
