### PR TITLE
Recipe form

### PR DESCRIPTION
**Pull request by AKSHATH99**
Created Page for recipe submission as mention in issue #18 

Also moved footer to a separate file and imported it to wherever necessary

### CODE REVIEW

**Comment by rudalkunwar** [comment]
hey recipe form is not showing on clicking the Submit Your Recipe

**Comment by AKSHATH99** [comment]
Let me look into it

**Comment by AKSHATH99** [comment]
@rudalkunwar review

**Comment by rudalkunwar** [comment]
Nice work!

**Comment by AKSHATH99** [comment]
Thank you !

**Pull request merged**
